# Randomized search CV for the partly additive XGB model

- Rerunning takes ~ten minutes
- Results might depend on seed
- Basically a copy of Chapter 3 code

In [1]:
# Rerunning takes ~10 minutes; results might depend on seed
import json

import pandas as pd
from joblib import load
from sklearn.model_selection import ParameterSampler  # , ParameterGrid
from tqdm import tqdm

import xgboost as xgb
from xgboost import XGBRegressor

grid_file = "grid_partly_additive_xgb.txt"

# Data splits already prepared in exercise text (must run first)
X_train, X_test, y_train, y_test = load("data.joblib")

# Data interface of XGBoost
dtrain = xgb.DMatrix(X_train, label=y_train)

# STEP 1: Model for the expected claims frequency
# -> Gamma deviance is both strictly consistent and meaningful

interaction_constraints = [
    ["DateNum"],
    ["Female"],
    [
        "LogInitial",
        "LogWeeklyPay",
        "LogDelay",
        "LogAge",
        "PartTime",
        "Married",
        "WeekDay",
        "Hour",
    ],
]

# STEP 2: Select learning rate to get reasonable number of trees by early stopping
params = {
    "objective": "reg:gamma",
    "learning_rate": 0.05,
    "max_depth": 2,
    "interaction_constraints": interaction_constraints,
}

In [2]:
# k-fold cross-validation to see if number of trees is reasonable
cvm = xgb.cv(
    params=params,
    dtrain=dtrain,
    num_boost_round=5000,
    nfold=5,
    early_stopping_rounds=20,
    callbacks=[xgb.callback.EvaluationMonitor(period=50)],
)

# A LR of 0.05 provides about 450 trees, which is ok
print("Best boosting round with default params:\n")
cvm.tail(1)

[0]	train-gamma-deviance:4.79567	test-gamma-deviance:4.80129
[50]	train-gamma-deviance:3.49601	test-gamma-deviance:3.59794
[100]	train-gamma-deviance:3.39817	test-gamma-deviance:3.54759
[150]	train-gamma-deviance:3.34944	test-gamma-deviance:3.52503
[200]	train-gamma-deviance:3.31681	test-gamma-deviance:3.51095
[250]	train-gamma-deviance:3.29105	test-gamma-deviance:3.50542
[289]	train-gamma-deviance:3.27606	test-gamma-deviance:3.50670
Best boosting round with default params:

,train-gamma-deviance-mean,train-gamma-deviance-std,test-gamma-deviance-mean,test-gamma-deviance-std
269,3.283436,0.023632,3.505074,0.216252

In [3]:
# STEP 3: Iterate randomized SearchCV for regularization parameters
if True:
    # Or ParameterGrid(...) if grid is small enough to check all combinations
    grid = ParameterSampler(
        {
            "objective": ["reg:gamma"],
            "learning_rate": [0.05],
            "max_depth": [2],
            "interaction_constraints": [interaction_constraints],
            "colsample_bynode": [0.8, 1],
            "subsample": [0.8, 1],
            "reg_lambda": [0, 1, 2, 3],
            "reg_alpha": [0, 1, 2, 3],
            "min_split_loss": [0, 0.001],
        },
        n_iter=50,
        random_state=9,
    )

    # Iterate over grid and save relevant information on disk
    search = []
    for g in tqdm(grid):
        cvm = xgb.cv(
            params=g,
            dtrain=dtrain,
            num_boost_round=5000,
            nfold=5,
            seed=67,
            early_stopping_rounds=20,
        )
        # Keep number of rounds, cv score, train score, and parameters
        search.append((len(cvm), *cvm.iloc[-1, [2, 0]], g))

        with open(grid_file, "w") as f:
            json.dump(search, f)

# Load grid and check (A) sort order and (B) if grid ranges were set reasonable
with open(grid_file) as f:
    search = json.load(f)

search_df = pd.DataFrame.from_records(
    search, columns=["num_boost_round", "cv_score", "train_score", "params"]
).sort_values("cv_score")

with pd.option_context("display.max_colwidth", None):
    display(search_df.head())

100%|██████████| 50/50 [03:55<00:00,  4.72s/it]

,num_boost_round,cv_score,train_score,params
0,297,3.483614,3.264127,"{'subsample': 0.8, 'reg_lambda': 0, 'reg_alpha': 1, 'objective': 'reg:gamma', 'min_split_loss': 0, 'max_depth': 2, 'learning_rate': 0.05, 'interaction_constraints': [['DateNum'], ['Female'], ['LogInitial', 'LogWeeklyPay', 'LogDelay', 'LogAge', 'PartTime', 'Married', 'WeekDay', 'Hour']], 'colsample_bynode': 0.8}"
40,304,3.484004,3.261707,"{'subsample': 0.8, 'reg_lambda': 0, 'reg_alpha': 0, 'objective': 'reg:gamma', 'min_split_loss': 0.001, 'max_depth': 2, 'learning_rate': 0.05, 'interaction_constraints': [['DateNum'], ['Female'], ['LogInitial', 'LogWeeklyPay', 'LogDelay', 'LogAge', 'PartTime', 'Married', 'WeekDay', 'Hour']], 'colsample_bynode': 0.8}"
21,281,3.484415,3.271415,"{'subsample': 0.8, 'reg_lambda': 1, 'reg_alpha': 3, 'objective': 'reg:gamma', 'min_split_loss': 0, 'max_depth': 2, 'learning_rate': 0.05, 'interaction_constraints': [['DateNum'], ['Female'], ['LogInitial', 'LogWeeklyPay', 'LogDelay', 'LogAge', 'PartTime', 'Married', 'WeekDay', 'Hour']], 'colsample_bynode': 0.8}"
37,297,3.484416,3.264375,"{'subsample': 0.8, 'reg_lambda': 2, 'reg_alpha': 0, 'objective': 'reg:gamma', 'min_split_loss': 0.001, 'max_depth': 2, 'learning_rate': 0.05, 'interaction_constraints': [['DateNum'], ['Female'], ['LogInitial', 'LogWeeklyPay', 'LogDelay', 'LogAge', 'PartTime', 'Married', 'WeekDay', 'Hour']], 'colsample_bynode': 0.8}"
14,301,3.484719,3.263508,"{'subsample': 0.8, 'reg_lambda': 2, 'reg_alpha': 2, 'objective': 'reg:gamma', 'min_split_loss': 0, 'max_depth': 2, 'learning_rate': 0.05, 'interaction_constraints': [['DateNum'], ['Female'], ['LogInitial', 'LogWeeklyPay', 'LogDelay', 'LogAge', 'PartTime', 'Married', 'WeekDay', 'Hour']], 'colsample_bynode': 0.8}"

In [4]:
# Best parameters
best = search_df.iloc[0]
best.num_boost_round, best.params

(np.int64(297),
 {'subsample': 0.8,
  'reg_lambda': 0,
  'reg_alpha': 1,
  'objective': 'reg:gamma',
  'min_split_loss': 0,
  'max_depth': 2,
  'learning_rate': 0.05,
  'interaction_constraints': [['DateNum'],
   ['Female'],
   ['LogInitial',
    'LogWeeklyPay',
    'LogDelay',
    'LogAge',
    'PartTime',
    'Married',
    'WeekDay',
    'Hour']],
  'colsample_bynode': 0.8})

In [6]:
# Fit on best parameters
model_xgb = XGBRegressor(
    **best.params, n_estimators=best.num_boost_round, random_state=59
)
_ = model_xgb.fit(X=X_train, y=y_train)