# Randomized search CV for the additive XGB model

- Rerunning takes ~ten minutes
- Results might depend on seed
- Basically a copy of Chapter 3 code

In [1]:
# Rerunning takes ~10 minutes; results might depend on seed
import json

import pandas as pd
from joblib import load
from sklearn.model_selection import ParameterSampler  # , ParameterGrid
from tqdm import tqdm

import xgboost as xgb
from xgboost import XGBRegressor

grid_file = "grid_additive_xgb.txt"

# Data splits already prepared in exercise text (must run first)
X_train, X_test, y_train, y_test = load("data.joblib")

# Data interface of XGBoost
dtrain = xgb.DMatrix(X_train, label=y_train)

# STEP 1: Model for the expected claims frequency
# -> Gamma deviance is both strictly consistent and meaningful

# STEP 2: Select learning rate to get reasonable number of trees by early stopping
params = {
    "objective": "reg:gamma",
    "learning_rate": 0.1,
    "max_depth": 1,  # for additivity
}

In [2]:
# k-fold cross-validation to see if number of trees is reasonable
cvm = xgb.cv(
    params=params,
    dtrain=dtrain,
    num_boost_round=5000,
    nfold=5,
    early_stopping_rounds=20,
    callbacks=[xgb.callback.EvaluationMonitor(period=50)],
)

# A LR of 0.1 provides about 550 trees, which is ok
print("Best boosting round with default params:\n")
cvm.tail(1)

[0]	train-gamma-deviance:4.69892	test-gamma-deviance:4.70086
[50]	train-gamma-deviance:3.51362	test-gamma-deviance:3.55734
[100]	train-gamma-deviance:3.43168	test-gamma-deviance:3.50687
[150]	train-gamma-deviance:3.39734	test-gamma-deviance:3.48239
[200]	train-gamma-deviance:3.37757	test-gamma-deviance:3.47098
[250]	train-gamma-deviance:3.36449	test-gamma-deviance:3.46524
[300]	train-gamma-deviance:3.35477	test-gamma-deviance:3.46139
[350]	train-gamma-deviance:3.34690	test-gamma-deviance:3.45744
[400]	train-gamma-deviance:3.34033	test-gamma-deviance:3.45427
[450]	train-gamma-deviance:3.33475	test-gamma-deviance:3.45259
[500]	train-gamma-deviance:3.32991	test-gamma-deviance:3.45161
[550]	train-gamma-deviance:3.32567	test-gamma-deviance:3.45041
[563]	train-gamma-deviance:3.32466	test-gamma-deviance:3.45049
Best boosting round with default params:

,train-gamma-deviance-mean,train-gamma-deviance-std,test-gamma-deviance-mean,test-gamma-deviance-std
543,3.326227,0.025619,3.450133,0.143542

In [3]:
# STEP 3: Iterate randomized SearchCV for regularization parameters
if True:
    # Or ParameterGrid(...) if grid is small enough to check all combinations
    grid = ParameterSampler(
        {
            "objective": ["reg:gamma"],
            "learning_rate": [0.1],
            "max_depth": [1],  # deciding for additivity
            "colsample_bynode": [0.8, 1],
            "subsample": [0.8, 1],
            "reg_lambda": [0, 1, 2, 3],
            "reg_alpha": [0, 1, 2, 3],
            "min_split_loss": [0, 0.001],
        },
        n_iter=50,
        random_state=9,
    )

    # Iterate over grid and save relevant information on disk
    search = []
    for g in tqdm(grid):
        cvm = xgb.cv(
            params=g,
            dtrain=dtrain,
            num_boost_round=5000,
            nfold=5,
            seed=67,
            early_stopping_rounds=20,
        )
        # Keep number of rounds, cv score, train score, and parameters
        search.append((len(cvm), *cvm.iloc[-1, [2, 0]], g))

        with open(grid_file, "w") as f:
            json.dump(search, f)

# Load grid and check (A) sort order and (B) if grid ranges were set reasonable
with open(grid_file) as f:
    search = json.load(f)

search_df = pd.DataFrame.from_records(
    search, columns=["num_boost_round", "cv_score", "train_score", "params"]
).sort_values("cv_score")

with pd.option_context("display.max_colwidth", None):
    display(search_df.head())

100%|██████████| 50/50 [05:19<00:00,  6.39s/it]

,num_boost_round,cv_score,train_score,params
41,552,3.454508,3.324399,"{'subsample': 1, 'reg_lambda': 0, 'reg_alpha': 2, 'objective': 'reg:gamma', 'min_split_loss': 0, 'max_depth': 1, 'learning_rate': 0.1, 'colsample_bynode': 0.8}"
6,548,3.454591,3.324743,"{'subsample': 1, 'reg_lambda': 2, 'reg_alpha': 2, 'objective': 'reg:gamma', 'min_split_loss': 0, 'max_depth': 1, 'learning_rate': 0.1, 'colsample_bynode': 0.8}"
34,548,3.454591,3.324743,"{'subsample': 1, 'reg_lambda': 2, 'reg_alpha': 2, 'objective': 'reg:gamma', 'min_split_loss': 0.001, 'max_depth': 1, 'learning_rate': 0.1, 'colsample_bynode': 0.8}"
27,552,3.454636,3.324528,"{'subsample': 1, 'reg_lambda': 3, 'reg_alpha': 3, 'objective': 'reg:gamma', 'min_split_loss': 0, 'max_depth': 1, 'learning_rate': 0.1, 'colsample_bynode': 0.8}"
7,554,3.454669,3.324124,"{'subsample': 1, 'reg_lambda': 1, 'reg_alpha': 1, 'objective': 'reg:gamma', 'min_split_loss': 0.001, 'max_depth': 1, 'learning_rate': 0.1, 'colsample_bynode': 0.8}"

In [4]:
# Best parameters
best = search_df.iloc[0]
best.num_boost_round, best.params

(np.int64(552),
 {'subsample': 1,
  'reg_lambda': 0,
  'reg_alpha': 2,
  'objective': 'reg:gamma',
  'min_split_loss': 0,
  'max_depth': 1,
  'learning_rate': 0.1,
  'colsample_bynode': 0.8})

In [5]:
# Fit on best parameters
model_xgb = XGBRegressor(
    **best.params, n_estimators=best.num_boost_round, random_state=59
)
_ = model_xgb.fit(X=X_train, y=y_train)